cmake_minimum_required(VERSION 3.15)
project(mouse-hardware-fix CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE Release)
endif()

if(WIN32)
  add_executable(mouse-hardware-fix WIN32 mouse-hardware-fix-windows.cpp)
  if(MINGW)
    target_link_options(mouse-hardware-fix PRIVATE -municode -static)
  endif()
  if(MSVC)
    set_property(TARGET mouse-hardware-fix PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded")
  endif()
else()
  add_executable(mouse-hardware-fix mouse-hardware-fix.cpp)

  include(GNUInstallDirs)
  install(TARGETS mouse-hardware-fix DESTINATION ${CMAKE_INSTALL_BINDIR})
  install(FILES 99-mouse-fix.rules DESTINATION lib/udev/rules.d)
  install(FILES mouse-hardware-fix@.service DESTINATION lib/systemd/system)
  install(FILES mouse-hardware-fix.conf DESTINATION ${CMAKE_INSTALL_SYSCONFDIR})
endif()

include(CTest)
if(BUILD_TESTING)
  add_executable(filter-test tests/filter-test.cpp)
  target_include_directories(filter-test PRIVATE ${CMAKE_SOURCE_DIR})
  add_test(NAME filter-test COMMAND filter-test)
endif()
