# Global configuration for mouse-hardware-fix
# 
# To disable specific fixes, add the flags to EXTRA_ARGS.
# Available flags:
#   --disable-scroll
#   --disable-click
#   --scroll-timeout <sec> (Default: 0.400)
#   --click-timeout <sec>  (Default: 0.025)

EXTRA_ARGS=""
